paths:
  data_root: "data"

datasets:
  gsm8k:
    path: "gsm8k_train.jsonl"
    graders:
      - math_exact
      - number_only
    multiplicative_graders:
      - length_cap_guard
    grader_weights:
      - 2.0
      - 1.0

stages:
  - name: main
    until_step: 100
    datasets:
      - id: gsm8k
        weight: 1.0

external_graders: {}

python_graders:
  length_cap_guard:
    builtin: completion_length_cap
    init_kwargs:
      max_completion_tokens: 200
